### PR TITLE
Generic Type Fixes

### PR DESCRIPTION
**Pull request by hsiangkuotang**
- Fixed nested generic type (e.g. A<B<C<D>>>) by introducing genericBraceCount variable to track current brace level during parsing EntityName
- Fixed generic types with trailing reference character (e.g. A<B>&) by removing the assumption that closing brace is in the end of string to be parsed

### CODE REVIEW

**Comment by preseverence** [comment]
First change (generic braces) is OK, but the second change breaks method naming (see SomethingWickedTest).
Can you provide an example of the situation you want to fix? You may add it into test xmls to check your changes.

**Comment by hsiangkuotang** [comment]
Sorry I missed a change in EntityName.cs in this PR. I am testing a library with a method like:

`<renamedMethod oldName="[TestApp1]TestClass1::TestMethod[7]([TestApp1]TestClass1.TestType1,[System.Globalization]System.Globalization.CultureInfo&,[System.Runtime]System.Nullable`1<TestClass1.TestType2>&,[System.Runtime]System.Nullable`1<TestClass1.TestType3>&,[System.Runtime]System.Nullable`1<TestClass1.TestType4>&,[System.Runtime]System.Nullable`1<System.Int32>&,[System.Runtime]System.String&)" newName="A" />
` 
There are several "System.Nullable`1<T>&" types. If there is no trailing '&' the generic param type T can be parsed correctly and put into genericParams. However with trailing '&', genericParams is null. With SimplifyNullable is on (by default) and there is no null check for genericParam in the getter of EntityName::Name, exception is thrown.

Will try to have second push with test cases...

**Comment by hsiangkuotang** [comment]
Sorry I missed a change in EntityName.cs in this PR. I am testing a library with a method like:

<renamedMethod 
oldName="[TestApp1]TestClass1::TestMethod[7]([TestApp1]TestClass1.TestType1,[System.Globalization]System.Globalization.CultureInfo&,[System.Runtime]System.Nullable`1<TestClass1.TestType2>&,[System.Runtime]System.Nullable`1<TestClass1.TestType3>&,[System.Runtime]System.Nullable`1<TestClass1.TestType4>&,[System.Runtime]System.Nullable`1<System.Int32>&,[System.Runtime]System.String&)" 
newName="A" />

There are several "System.Nullable`1<T>&" types. If there is no trailing '&' the generic param type T can be parsed correctly and put into genericParams. However with trailing '&', genericParams is null. With SimplifyNullable is on (by default) and there is no null check for genericParam in the getter of EntityName::Name, exception is thrown.

Will try to have second push with test cases...

**Comment by hsiangkuotang** [comment]
Sorry I missed a change in EntityName.cs in this PR. I am testing a library with a renamed method as:

"[TestApp1]TestClass1::TestMethod[7]([TestApp1]TestClass1.TestType1,[System.Globalization]System.Globalization.CultureInfo&,[System.Runtime]System.Nullable`1<TestClass1.TestType2>&,[System.Runtime]System.Nullable`1<TestClass1.TestType3>&,[System.Runtime]System.Nullable`1<TestClass1.TestType4>&,[System.Runtime]System.Nullable`1<System.Int32>&,
[System.Runtime]System.String&)" 

There are several "System.Nullable`1<T>&" types. If there is no trailing '&' the generic param type T can be parsed correctly and put into genericParams. However with trailing '&', genericParams is null. With SimplifyNullable is on (by default) and there is no null check for genericParam in the getter of EntityName::Name, exception is thrown.

Will try to have second push with test cases...

**Comment by preseverence** [comment]
Created test for ``void Method(Dictionary<string, List<string>>`` and don't see the first bug. Test passed on first try.
The second problem is more interesting. Trying to do something like ``void Method(ref int? a)`` breaks parsing... I'll fix it by my own.

**Comment by preseverence** [comment]
Ref args and its combination with generics are supported:  1c343c02e41b44d392348a233182e64cb2e0cd61.

See EmbeddedGenericMethodTest for the first bug. If I missed something and test doesn't shows it, please make right test and another PR.

**Pull request closed without merging**
